# Generated by Django 3.2.6 on 2021-08-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('general', 'Umumiy'), ('man', 'Erkak'), ('woman', 'Ayol'), ('children', 'Bolalar')], default='general', max_length=200),
        ),
    ]
